apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: thomson-dev-eventlistener
  namespace: thomson-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: thomson-dev-trigger